# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Stallion.destroy_all
stallions_attributes = [
  {
    name: "Man o War",
    average_rating: "9",
    category: "Working Horses",
    breed: "Belgian Warmblood",
    lineage: "confirmed",
    colour: "black",
    description: "Awesone Sire!",
    country: "Belgium",
    town: "Kortrijk",
    image: "Belgian_Warmblood.png",
  },
  {
    name: "Native Dancer",
    average_rating: "8",
    category: "Working Horses",
    breed: "Clydesdale",
    lineage: "confirmed",
    colour: "brown",
    description: "Awesone Sire!",
    country: "Belgium",
    town: "Ghent",
    image: "Clydesdale.JPG",
  },
  {
    name: "Buckpasser",
    average_rating: "7",
    category: "Working Horses",
    breed: "Shire Horse",
    lineage: "confirmed",
    colour: "white",
    description: "Awesone Sire!",
    country: "Belgium",
    town: "Waterloo",
    image: "Shire.jpg",
  },
  {
    name: "Shared Belief",
    average_rating: "8",
    category: "Race Horses",
    breed: "Arabian",
    lineage: "confirmed",
    colour: "grey",
    description: "Awesone Sire!",
    country: "France",
    town: "Marseille",
    image: "Arabian_Horse.jpg",
  },
  {
    name: "Whirlaway",
    average_rating: "9",
    category: "Race Horses",
    breed: "Quarterhorse",
    lineage: "confirmed",
    colour: "black",
    description: "Awesone Sire!",
    country: "The Netherlands",
    town: "The Hague",
    image: "Quarterhorse.jpg",
  },
  {
    name: "Genuine Risk",
    average_rating: "10",
    category: "Race Horses",
    breed: "Thoroughbred",
    lineage: "confirmed",
    colour: "brown",
    description: "Awesone Sire!",
    country: "United Arab Emirates",
    town: "Dubai",
    image: "thoroughbred.jpg",
  },
  {
    name: "Princess Rooney",
    average_rating: "7",
    category: "Jumping Horses",
    breed: "Pecheron",
    lineage: "confirmed",
    colour: "grey",
    description: "Awesone Sire!",
    country: "Germany",
    town: "Frankfurt",
    image: "Pecheron.jpg",
  },
  {
    name: "Palace Malice",
    average_rating: "9",
    category: "Jumping Horses",
    breed: "Apaloosa",
    lineage: "confirmed",
    colour: "black",
    description: "Awesone Sire!",
    country: "Belgium",
    town: "Luxembourg",
    image: "Apaloosa.jpg",
  },
  {
    name: "Wise Dan",
    average_rating: "8",
    category: "Jumping Horses",
    breed: "American Paint",
    lineage: "confirmed",
    colour: "brown",
    description: "Awesone Sire!",
    country: "France",
    town: "Paris",
    image: "American-Paint-Horse.jpg",
  },
  {
    name: "Ruffian",
    average_rating: "7",
    category: "Rodeo Horses",
    breed: "Fjord Horse",
    lineage: "confirmed",
    colour: "black",
    description: "Awesone Sire!",
    country: "Spain",
    town: "Cordoba",
    image: "flord_horse.jpg",
  },
  {
    name: "Seattle Slew",
    average_rating: "5",
    category: "Rodeo Horses",
    breed: "Nokota",
    lineage: "confirmed",
    colour: "white",
    description: "Awesone Sire!",
    country: "Spain",
    town: "Bilbao",
    image: "Nokota.jpg",
  },
  {
    name: "American Pharoah",
    average_rating: "10",
    category: "Rodeo Horses",
    breed: "Chilean",
    lineage: "confirmed",
    colour: "white",
    description: "Awesone Sire!",
    country: "United Arab Emirates",
    town: "Abu Dhabi",
    image: "Chilean_Horse.jpg",
  }
]
stallions_attributes.each { |params| Stallion.create!(params) }
